sonar.projectKey=vtp_qlda_fe-develop
sonar.projectName=VTP QLDA FE
sonar.projectVersion=1.0
# Chỉ scan code trong các thư mục src
sonar.sources=src

# Encoding
sonar.sourceEncoding=UTF-8

# L?c file qu�t (code)
sonar.inclusions=**/*.ts,**/*.js,**/*.html,**/*.css,**/*.scss
sonar.exclusions=**/*.json,**/*.sh,**/*.bat,**/*.md,**/*.yml,**/test/**,**/mock/**,**/resources/static/**

# SonarQube server
sonar.host.url=https://sonarqube.viettelsoftware.com
sonar.login=squ_93e3346c4601914b23f02ba0e2c096cb224a1d6e
