name: Deploy Angular

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Dùng bản 22 để ổn định

      - name: Install
        run: npm install --legacy-peer-deps

      - name: Build
        run: npx ng build --configuration production --base-href /vtp_qlda_fe/

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          # Kiểm tra lại folder này trong máy bạn sau khi build xong
          path: ./dist/vtp_qlda_fe/browser

      - name: Deploy
        uses: actions/deploy-pages@v4