name: Deploy Angular

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Lên hẳn bản 24 cho đồng bộ với server 2026

      - name: Install
        run: npm install --legacy-peer-deps

      - name: Build
        run: npx ng build --configuration production --base-href /vtp_qlda_fe/

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          # TÔI ĐÃ SỬA DÒNG NÀY: Bỏ /browser để khớp với đa số cấu hình Angular mặc định
          path: ./dist/vtp_qlda_fe

      - name: Deploy
        uses: actions/deploy-pages@v4