name: Deploy Angular to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        # Đảm bảo /vtp_qlda_fe/ đúng là tên repo của bạn trên GitHub
        run: npx ng build --configuration production --base-href /vtp_qlda_fe/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # THỬ NGHIỆM 1: Nếu vẫn lỗi 404, bạn hãy thử đổi thành './dist/vss' (bỏ /browser)
          # Nhưng với log build trước đó của bạn, đường dẫn này là khả thi nhất:
          path: ./dist/vss/browser

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4